### ISSUE TITLE
service dyndns not parseable 

### ISSUE THREAD

**Issue by network-shark** [hedin/vyatta-conf-parser#6]
Hey @hedin , 

could you please check the following syntax . I tried to debug it as far as I can . 

```
service {
    dns {
        dynamic {
            interface pppoe0 {
                service dyndns {
                    host-name example.com
                    login exampleuser
                    password ****
                    server dyn.dns.he.net
                }
            }
        }
        forwarding {
            cache-size 1000
            listen-on switch0
            name-server 1.1.1.1
            system
        }
    }
}
```

```
Traceback (most recent call last):
  File "./vyatta.py", line 15, in <module>
    conf_dict = vyattaconfparser.parse_conf(data)
  File "/Users/sharky/.pyenv/versions/salt/lib/python3.7/site-packages/vyattaconfparser/parser.py", line 143, in parse_conf
    c, headers = parse_node(c, line, n, headers)
  File "/Users/sharky/.pyenv/versions/salt/lib/python3.7/site-packages/vyattaconfparser/parser.py", line 132, in parse_node
    line=line))
vyattaconfparser.parser.ParserException: Parse error in
 20: }
```

```
service {
    dns {
        dynamic {
            interface pppoe0 {
               
            }
        }
        forwarding {
            cache-size 1000
            listen-on switch0
            name-server 1.1.1.1
            system
        }
    }
}
```

I remove the service dyndns than your library is able to parse the file. 

```
service {
    dns {
        dynamic {
            interface pppoe0 {
               
            }
        }
        forwarding {
            cache-size 1000
            listen-on switch0
            name-server 1.1.1.1
            system
        }
    }
}

```
```
{'service': {'dns': {'dynamic': {'interface': {'pppoe0': {}}}, 'forwarding': {'cache-size': '1000', 'listen-on': 'switch0', 'name-server': '1.1.1.1', 'system': 'system'}}}}
```

**Comment by network-shark** [comment]
I found the problem.

"service" is not uniq . 

If I replace service dyndns with "service1 dyndns" . The parser works. 
```
service {
    dns {
        dynamic {
            interface pppoe0 {
                    service dyndns {               <-----------
                    host-name example.com
                    login exampleuser
                    password ****
                    server dyn.dns.he.net
                }
            }
        }
        forwarding {
            cache-size 1000
            listen-on switch0
            name-server 1.1.1.1
            system
        }
    }
}
```

**Comment by miron0xff** [comment]
Hi @network-shark , thank you for the report. Fixed this in master.
New version 0.5.2 is on PyPI now.
